----------------------------------------------------------------------------------------
SVMTool v1.3.1
(C) 2009 TALP RESEARCH CENTER.
Written by Jesus Gimenez and Lluis Marquez.
----------------------------------------------------------------------------------------
TRAINING SET = /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

CREATING DICTIONARY <ndt-optimized.DICT> FROM </home/pettehoh/master/data/optimized/training-optimized-gold-svmtool>
AUTOMATICALLY REPAIRING DICTIONARY <ndt-optimized.DICT> [0.001] (#REPAIRINGS = 24)
DICTIONARY <ndt-optimized.DICT> [30076 words]

*********************************************************************************************
BUILDING MODELS... [MODE = 0 :: DIRECTON = LR]
*********************************************************************************************


=============================================================================================
=============================================================================================
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
BUILDING MODELS ON WHOLE CORPUS </home/pettehoh/master/data/optimized/training-optimized-gold-svmtool>
C PARAMETER [MODE = 0 :: DIRECTON = LR]:   KNOWN [ C = 0 ] :: UNKNOWN [ C = 0 ]
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
---------------- KNOWN WORDS... [MODE = 0 :: DIRECTON = LR] -------------------
FEATURE EXTRACTION from < /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool > onto < ndt-optimized.M0.LR.SAMPLES > ......244776 WORDS [DONE]
MAKING MAPPING from <ndt-optimized.M0.LR.SAMPLES>... [DONE]
WRITING MAPPING <ndt-optimized.M0.LR.SAMPLES.MAP>... [FREQ = 1] :: [SIZE = 607845] [DONE]
MAPPING DATA FEATURES from <ndt-optimized.M0.LR.SAMPLES> to <ndt-optimized.M0.LR.SAMPLES.DSF>.....75847 [DONE]
LEARNING SVM MODELS... [C = 0] ..<anf>..<parentes-slutt>..adj..adj|komp..adj|pos..adj|sup..adv..det..det|be..inf-merke..interj..konj..prep..pron..pron|pers..pron|pers|akk..pron|pers|nom..pron|sp..sbu..subst..subst|appell..subst|appell|be..subst|appell|be|gen..subst|appell|ub..subst|appell|ub|gen..subst|prop..subst|prop|gen..symb..ukjent..verb|fin..verb|infin [DONE]
BENCHMARK TIME: 98.0000
---------------- UNKNOWN WORDS... [MODE = 0 :: DIRECTON = LR] -------------------
FEATURE EXTRACTION from < /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool > onto < ndt-optimized.UNK.M0.LR.SAMPLES > ......244776 WORDS [DONE]
MAKING MAPPING from <ndt-optimized.UNK.M0.LR.SAMPLES>... [DONE]
WRITING MAPPING <ndt-optimized.UNK.M0.LR.SAMPLES.MAP>... [FREQ = 1] :: [SIZE = 293134] [DONE]
MAPPING DATA FEATURES from <ndt-optimized.UNK.M0.LR.SAMPLES> to <ndt-optimized.UNK.M0.LR.SAMPLES.DSF>.....25333 [DONE]
LEARNING SVM MODELS... [C = 0] ..<parentes-beg>..<parentes-slutt>..adj..adj|komp..adj|pos..adj|sup..adv..clb..det..det|be..det|ub..interj..konj..prep..pron..pron|pers..pron|pers|akk..pron|pers|nom..sbu..subst..subst|appell..subst|appell|be..subst|appell|be|gen..subst|appell|ub..subst|appell|ub|gen..subst|prop..subst|prop|gen..symb..ukjent..verb..verb|fin..verb|infin [DONE]
BENCHMARK TIME: 88.0000
----------------------------------------------------------------------------------------
SVMTool v1.3.1
(C) 2009 TALP RESEARCH CENTER.
Written by Jesus Gimenez and Lluis Marquez.
----------------------------------------------------------------------------------------
TRAINING SET = /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

CREATING DICTIONARY <ndt-optimized.DICT> FROM </home/pettehoh/master/data/optimized/training-optimized-gold-svmtool>
AUTOMATICALLY REPAIRING DICTIONARY <ndt-optimized.DICT> [0.001] (#REPAIRINGS = 24)
DICTIONARY <ndt-optimized.DICT> [30076 words]

*********************************************************************************************
BUILDING MODELS... [MODE = 1 :: DIRECTON = LR]
*********************************************************************************************


=============================================================================================
=============================================================================================
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
BUILDING MODELS ON WHOLE CORPUS </home/pettehoh/master/data/optimized/training-optimized-gold-svmtool>
C PARAMETER [MODE = 1 :: DIRECTON = LR]:   KNOWN [ C = 0 ] :: UNKNOWN [ C = 0 ]
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
---------------- KNOWN WORDS... [MODE = 1 :: DIRECTON = LR] -------------------
FEATURE EXTRACTION from < /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool > onto < ndt-optimized.M1.LR.SAMPLES > ......244776 WORDS [DONE]
MAKING MAPPING from <ndt-optimized.M1.LR.SAMPLES>... [DONE]
WRITING MAPPING <ndt-optimized.M1.LR.SAMPLES.MAP>... [FREQ = 1] :: [SIZE = 610849] [DONE]
MAPPING DATA FEATURES from <ndt-optimized.M1.LR.SAMPLES> to <ndt-optimized.M1.LR.SAMPLES.DSF>.....75847 [DONE]
LEARNING SVM MODELS... [C = 0] ..<anf>..<parentes-slutt>..adj..adj|komp..adj|pos..adj|sup..adv..det..det|be..inf-merke..interj..konj..prep..pron..pron|pers..pron|pers|akk..pron|pers|nom..pron|sp..sbu..subst..subst|appell..subst|appell|be..subst|appell|be|gen..subst|appell|ub..subst|appell|ub|gen..subst|prop..subst|prop|gen..symb..ukjent..verb|fin..verb|infin [DONE]
BENCHMARK TIME: 105.0000
---------------- UNKNOWN WORDS... [MODE = 1 :: DIRECTON = LR] -------------------
FEATURE EXTRACTION from < /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool > onto < ndt-optimized.UNK.M1.LR.SAMPLES > ......244776 WORDS [DONE]
MAKING MAPPING from <ndt-optimized.UNK.M1.LR.SAMPLES>... [DONE]
WRITING MAPPING <ndt-optimized.UNK.M1.LR.SAMPLES.MAP>... [FREQ = 1] :: [SIZE = 287082] [DONE]
MAPPING DATA FEATURES from <ndt-optimized.UNK.M1.LR.SAMPLES> to <ndt-optimized.UNK.M1.LR.SAMPLES.DSF>.....25333 [DONE]
LEARNING SVM MODELS... [C = 0] ..<parentes-beg>..<parentes-slutt>..adj..adj|komp..adj|pos..adj|sup..adv..clb..det..det|be..det|ub..interj..konj..prep..pron..pron|pers..pron|pers|akk..pron|pers|nom..sbu..subst..subst|appell..subst|appell|be..subst|appell|be|gen..subst|appell|ub..subst|appell|ub|gen..subst|prop..subst|prop|gen..symb..ukjent..verb..verb|fin..verb|infin [DONE]
BENCHMARK TIME: 98.0000
----------------------------------------------------------------------------------------
SVMTool v1.3.1
(C) 2009 TALP RESEARCH CENTER.
Written by Jesus Gimenez and Lluis Marquez.
----------------------------------------------------------------------------------------
TRAINING SET = /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool
----------------------------------------------------------------------------------------
----------------------------------------------------------------------------------------

CREATING DICTIONARY <ndt-optimized.DICT> FROM </home/pettehoh/master/data/optimized/training-optimized-gold-svmtool>
AUTOMATICALLY REPAIRING DICTIONARY <ndt-optimized.DICT> [0.001] (#REPAIRINGS = 24)
DICTIONARY <ndt-optimized.DICT> [30076 words]

*********************************************************************************************
BUILDING MODELS... [MODE = 2 :: DIRECTON = LR]
*********************************************************************************************


=============================================================================================
=============================================================================================
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
BUILDING MODELS ON WHOLE CORPUS </home/pettehoh/master/data/optimized/training-optimized-gold-svmtool>
C PARAMETER [MODE = 2 :: DIRECTON = LR]:   KNOWN [ C = 0 ] :: UNKNOWN [ C = 0 ]
---------------------------------------------------------------------------------------------
---------------------------------------------------------------------------------------------
---------------- KNOWN WORDS... [MODE = 2 :: DIRECTON = LR] -------------------
FEATURE EXTRACTION from < /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool > onto < ndt-optimized.M2.LR.SAMPLES > ......244776 WORDS [DONE]
MAKING MAPPING from <ndt-optimized.M2.LR.SAMPLES>... [DONE]
WRITING MAPPING <ndt-optimized.M2.LR.SAMPLES.MAP>... [FREQ = 1] :: [SIZE = 570231] [DONE]
MAPPING DATA FEATURES from <ndt-optimized.M2.LR.SAMPLES> to <ndt-optimized.M2.LR.SAMPLES.DSF>.....75847 [DONE]
LEARNING SVM MODELS... [C = 0] ..<anf>..<parentes-slutt>..adj..adj|komp..adj|pos..adj|sup..adv..det..det|be..inf-merke..interj..konj..prep..pron..pron|pers..pron|pers|akk..pron|pers|nom..pron|sp..sbu..subst..subst|appell..subst|appell|be..subst|appell|be|gen..subst|appell|ub..subst|appell|ub|gen..subst|prop..subst|prop|gen..symb..ukjent..verb|fin..verb|infin [DONE]
BENCHMARK TIME: 86.0000
---------------- UNKNOWN WORDS... [MODE = 2 :: DIRECTON = LR] -------------------
FEATURE EXTRACTION from < /home/pettehoh/master/data/optimized/training-optimized-gold-svmtool > onto < ndt-optimized.UNK.M2.LR.SAMPLES > ......244776 WORDS [DONE]
MAKING MAPPING from <ndt-optimized.UNK.M2.LR.SAMPLES>... [DONE]
WRITING MAPPING <ndt-optimized.UNK.M2.LR.SAMPLES.MAP>... [FREQ = 1] :: [SIZE = 276386] [DONE]
MAPPING DATA FEATURES from <ndt-optimized.UNK.M2.LR.SAMPLES> to <ndt-optimized.UNK.M2.LR.SAMPLES.DSF>.....25333 [DONE]
LEARNING SVM MODELS... [C = 0] ..<parentes-beg>..<parentes-slutt>..adj..adj|komp..adj|pos..adj|sup..adv..clb..det..det|be..det|ub..interj..konj..prep..pron..pron|pers..pron|pers|akk..pron|pers|nom..sbu..subst..subst|appell..subst|appell|be..subst|appell|be|gen..subst|appell|ub..subst|appell|ub|gen..subst|prop..subst|prop|gen..symb..ukjent..verb..verb|fin..verb|infin [DONE]
BENCHMARK TIME: 82.0000
